version: '3'
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
            network: host
        container_name: frontend-app
        volumes:
            - ./:/app
        ports:
            - 3000:3000

